name: 🧩 Check typescript code

on: 
  workflow_call:
    inputs:
      node-version:
        type: string
        description: "Node version"
        required: false
        default: "22"

jobs:
  check-typescript-code:
    name: Check typescript code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install and setup fnm and pnpm
        run: |
          curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "./.fnm" --skip-shell
          export PATH="./.fnm:$PATH"
          eval "$(fnm env --use-on-cd --shell bash)"
          fnm install ${{ inputs.node-version }}
          fnm use ${{ inputs.node-version }}
          npm install -g pnpm

      - name: Install dependencies
        run: |
          export PATH="./.fnm:$PATH"
          eval "$(fnm env --use-on-cd --shell bash)"
          pnpm i

      - name: Prettier (code formatter)
        run: |
          export PATH="./.fnm:$PATH"
          eval "$(fnm env --use-on-cd --shell bash)"
          pnpm prettier --check .
